[tool.poetry]
name = "Executor"
version = "0.1.0"
description = "A discord bot to run code from discord"
authors = ["Alexyy802 <techlolalexy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pistonapi = "^1.0.1"
Flask = "^2.0.2"
discord = "^1.7.3"
pytimeparse = "^1.1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
